### ISSUE TITLE
This tool is useless stop wasting your time

### ISSUE THREAD

**Issue by cpueasy** [erkexzcx/stoppropaganda#113]
https://www.google.com/maps/d/u/0/viewer?mid=1DZtmQOsq6UBodj8zgB9WC_9BEaY&ll=47.9415218726191%2C37.54165384070755&z=14
https://www.youtube.com/watch?v=i2ILlui2HmI man look at these violent hated separatists!
![image](https://user-images.githubusercontent.com/88821057/156931265-271bdab3-d314-4efc-b27b-3684a9a1f1ad.png)
https://en.wikipedia.org/wiki/Casualties_of_the_Russo-Ukrainian_War#:~:text=War%20in%20Donbas,-Main%20article%3A%20War&text=The%20overall%20number%20of%20confirmed,killed%20by%2013%20May%202021
https://www.hrw.org/news/2014/07/24/ukraine-unguided-rockets-killing-civilians
https://ru.wikinews.org/wiki/%D0%92_%D0%93%D0%BE%D1%80%D0%BB%D0%BE%D0%B2%D0%BA%D0%B5_%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D0%BB%D0%B8_%D0%BC%D0%B5%D0%BC%D0%BE%D1%80%D0%B8%D0%B0%D0%BB_%D0%BF%D0%BE%D0%B3%D0%B8%D0%B1%D1%88%D0%B8%D0%BC_%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D1%8F%D0%BC
https://ronin-077.livejournal.com/37466.html
Russia is Defending Ukraine not Invading. Know the truth. **STOP SUPPORTING TERRORISM**

**Comment by cpueasy** [comment]
![image](https://user-images.githubusercontent.com/88821057/156931364-5992a481-90ff-4495-8918-9e9a0d5afbc5.png)

**Comment by erkexzcx** [comment]
Alright, I have few questions for you. Depending on your IQ you might be able to answer them in human way without personal attacks:
- Why would Russia care of what is happening in Ukraine in the first place?
- Why would only Russia see Ukraine as a problem and not the rest of the world?
- Why Russia reportedly commit war crimes in Ukraine (killing unarmed civilians, shooting into nuclear reactors)?
- Why Putin continuously threatens non-NATO countries if they join NATO?

> Russia is Defending Ukraine not Invading.

From who?

> Know the truth.

That's some antivaxx shit.

> STOP SUPPORTING TERRORISM

I do, so I made this app.

**Comment by baylanger** [comment]
Educate yourself.  Ukraine territory DOES NOT belong to Russia.
[Ukraine History](https://en.wikipedia.org/wiki/Ukraine#History)

Your government, the Russian's owned media (tv, radio), the Russian mafia every moment they speak, they are brainwashing Russian citizens.  You live in Russia and understand English, fantastic.

Putin's **100 billions ruble** Palace paid with Russian citizens' money
[Google Satellite View](https://www.google.com/maps/@44.4212736,38.20606,2716m/data=!3m1!1e3) paid with Russian citizens' money
[Wikipedia](https://en.wikipedia.org/wiki/Putin's_Palace)

This is 1 of many examples, Putin, his allies/friends/family, they take your money.

**Comment by baylanger** [comment]
@cpueasy if I'd be in your shoes I'd be pissed right now.  Once you've come down from learning how bad your government spends your money, you mind helping us identifying more web sites that brainwash their citizens, like local news papers, small radio stations, etc?

**Comment by baylanger** [comment]
I would agree to remove the "Asshole" tag added to this issue.

**Comment by erkexzcx** [comment]
The fact that this user has access to the internet and still believes in Russian propaganda is just sad. The "Asshole" tag stays.

**Comment by baylanger** [comment]
Internet and reads English, can't go wrong - as you mentioned in your first reply, IQ related perhaps.  It might take him a few days to come down and get back to us.

**Comment by cpueasy** [comment]
@baylanger Yeah I'm so PRESSED LOL. It takes 10 seconds for Russia to Press a button and boom no Ukraine. Yet the war has been going on for a a week or so hasn't it? NOW Ask yourself **WHY**. That's right I can only launch DOS attacks because my skill level is BELOW **ZERO** and I can't hack anything for crap because I'm a pathetic Lithuanian skid @erkexzcx

**Comment by cpueasy** [comment]
Q: Why would Russia care of what is happening in Ukraine in the first place?

A: 15 thousand Russians killed by neo nazi rebels  over the past 8 years, nobody give a crap.

Q: Why would only Russia see Ukraine as a problem and not the rest of the world?

A: Search up Ukrainian nationalism and see who you and the rest of the world are supporting. Stephan Bandera is a terrorist btw.

Q: Why Russia reportedly commit war crimes in Ukraine (killing unarmed civilians, shooting into nuclear reactors, shelling cities with civilians)?

A: Where's your proof? I forgot you don't have any. Any Russians Tanks or vehicles have a "Z" for ZAPAD on them to show they are Russian so sending Random Ukrainian tanks running cars over simply won't cut it buddy.

Q: Why Putin continuously threatens non-NATO countries if they join NATO?

A: Did you see what they did to Yugoslavia? Literally worse than Ukraine in 1999. Let me Enlighten you. 
https://www.youtube.com/watch?v=gelCe981y0I

**Comment by cpueasy** [comment]
Putin's 100 billions ruble Palace paid with Russian citizens' money
[Google Satellite View](https://www.google.com/maps/@44.4212736,38.20606,2716m/data=!3m1!1e3)
[Wikipedia](https://en.wikipedia.org/wiki/Putin's_Palace)
You must have a screw loose in your brain because he lives in **KREMLIN MOSCOW** not in that palace that doesn't belong to him. Monkey brain

**Comment by erkexzcx** [comment]
> Q: Why would Russia care of what is happening in Ukraine in the first place?
> A: 15 thousand Russians killed by neo nazi rebels over the past 8 years, nobody give a crap.

Why there are no reports of killed russian's relatives/friends that actually live in Ukraine? Also why there are no `neo nazi rebels` reports as well? Also Germany said that this is purely bullshit as they are `kind of experts in this area`. You know there are on nazis in Ukraine.

> Q: Why would only Russia see Ukraine as a problem and not the rest of the world?
> A: Search up Ukrainian nationalism and see who you and the rest of the world are supporting. Stephan Bandera is a terrorist btw.

Why should I care about this dude? Zelenski is a president of Ukraine, not some random dude who died more than 50 years ago. According to your logic, Stalin used to be leader of russian territories, so should the rest of the world invade Russia now?

Let me guess - Stalin did nothing bad? :D even my grandpa would like to disagree with this statement.

> Q: Why Russia reportedly commit war crimes in Ukraine (killing unarmed civilians, shooting into nuclear reactors, shelling cities with civilians)?
> A: Where's your proof? I forgot you don't have any. Any Russians Tanks or vehicles have a "Z" for ZAPAD on them to show they are Russian so sending Random Ukrainian tanks running cars over simply won't cut it buddy.

Have you been antivaxxer as well? :D `Where's your proof?` is probably the most childish excuse you can find. Proof:
- Friends and relatives who live in Ukraine (they have internet and telephones as well).
- Friends/relatives of friends/relatives who live in Ukraine (they have internet and telephones as well).
- Telegram groups (video recordings, locals feedback, captured russian soldiers and their interrogation).

> Any Russians Tanks or vehicles have a "Z" for ZAPAD on them to show they are Russian so sending Random Ukrainian tanks running cars over simply won't cut it buddy.

Yes, tanks with Z are shooting into nuclear reactors and driving over civilian vehicles. On top of that they are shooting into civilians. Everything is shown in video recordings by Ukrainian civilians. But hey, government in russia knows better, right?

> Q: Why Putin continuously threatens non-NATO countries if they join NATO?
> A: Did you see what they did to Yugoslavia? Literally worse than Ukraine. Let me Enlighten you.
> https://www.youtube.com/watch?v=gelCe981y0I

NATO is defence alliance, not offence. Not sure why do you see a problem with that? From wikipedia `After attempts at a diplomatic solution failed, NATO intervened, justifying the campaign as a "humanitarian war". [55]` which means don't start a war against NATO and NATO will not bomb you. This includes nuclear reactors, which will definitelly impact NATO countries and NATO must act to protect themselves from nuclear explosions or further aggression against baltic countries.

But it also applies the same logic - russian had Stalin so the world should bomb russia now?

**Comment by erkexzcx** [comment]
To everyone reading this - I know this discussion is worthless and I am not trying to achieve anything. You can't change brainwashed people by russian propaganda just like you can't change antivaxxers.

Luckily thanks to sanctions they will sort themselves out :)

**Comment by erkexzcx** [comment]
@cpueasy what do you think about these? Please explain:
- Video/pictures recordings of actual people who lived those events?
- Stories of actual people who lived those events?
- Stories of friends/relatives who also lived those events?

Who is right - Russian government or actual people who experienced themselves?

**Comment by cpueasy** [comment]
To everyone reading this - I know this discussion is worthless and @erkexzcx is trying to achieve anything. You can't change brainwashed people by American propaganda just like you can't change <IRRELEVANT>

Luckily thanks to me being a lithuanian skid and ddosing russian sites because im harmless and can't hack my way out of a plastic bag they will sort themselves out :)

**Comment by cpueasy** [comment]
Video/pictures recordings of actual people who lived those events?
Stories of actual people who lived those events?
Stories of friends/relatives who also lived those events?

I literally sent you everything scroll up lazy clown

**Comment by cpueasy** [comment]
> Why there are no reports of killed russian's relatives/friends that actually live in Ukraine? Also why there are no neo nazi rebels reports as well? Also Germany said that this is purely bullshit as they are kind of experts in this area. You know there are on nazis in Ukraine.

You're blind and didn't even bother to open my sites I sent you. Stay blind pendoz

> Why should I care about this dude? Zelenski is a president of Ukraine, not some random dude who died more than 50 years ago. According to your logic, Stalin used to be leader of russian territories, so should the rest of the world invade Russia now?

Zelensky is the so called president but one wrong move from him and he's a dead man. He's a puppet to the terrorists that are currently controlling the country. Stalin is completely irrelevant just like your "anti vax" statements I could write you an essay on him but I really got no time for that. In all honesty he's a controversial figure and he even put his own relatives into gulags.

> Let me guess - Stalin did nothing bad? :D even my grandpa would like to disagree with this statement.

Again another Irrelevant statement, Like I could write you a whole essay on how tiny your Lithuania is and how irrelevant it is to the rest of the world. Your grandpa isn't Russian and is also completely irrelevant in this context of conversation.


> Have you been antivaxxer as well? :D Where's your proof? is probably the most childish excuse you can find. Proof:

Hey bro, can you help me find Lithuania on the map? I'm searching for a solid day and I just can't seem to find it anywhere!

> Friends and relatives who live in Ukraine (they have internet and telephones as well).
Friends/relatives of friends/relatives who live in Ukraine (they have internet and telephones as well).
Telegram groups (video recordings, locals feedback, captured russian soldiers and their interrogation).
Actual journalists from non-russian countries reporting the situation from Ukraine.

all your friends see and film are tanks and things getting destroyed. You can't provide me sufficient video evidence to show **ANYTHING** All those tanks destroying cars don't have the Z symbol, you might as well believe the ghost of Kiev exists you KNOBHEAD . Telegram groups oh yeah more things getting destroyed and random Ukrainians pretending to be Russian? very believable yet you claim that I'm "brainwashed" You're brainwashed you clown for even making this whole repo. 

> Yes, tanks with Z are shooting into nuclear reactors and driving over civilian vehicles. On top of that they are shooting into civilians. Everything is shown in video recordings by Ukrainian civilians. But hey, government in Russia knows better, right?

Video proof or it didn't happen. send it to my discord -> cpu_ezy [Zapad Team]#7008. Really everything recorded ayy? Everything everything 100% completely one sided? Well I'm proving your whole point wrong because Russian film too and Russian news exists 😮 crazy stuff right? Yeah Government in Russia does know better, they got a solid counter terrorism system in place and I completely respect that.


> NATO is defence alliance, not offence. Not sure why do you see a problem with that? From wikipedia After attempts at a diplomatic solution failed, NATO intervened, justifying the campaign as a "humanitarian war". [55] which means don't start a war against NATO and NATO will not bomb you. This includes nuclear reactors, which will definitelly impact NATO countries and NATO must act to protect themselves from nuclear explosions or further aggression against baltic countries.

Oh yeah. Lets bomb Yugoslavia that did nothing wrong with ** NUCLEAR WARHEADS** Because we want to prevent a "humanitarian war" let bomb Heroshima and Nagasaki for the same reason. Just to measure our huge private parts in front of the whole world. "NATO will not bomb you" -- @erkexzcx  (Head representative of NATO larping Lithuanian brainwashed skid) says to me. Oh yeah I totally legit 100% believe you speaking from behalf of NATO mhm yes yes 🤡 

"NATO must act to protect themselves" -- nah dude it's -> "Russia must act to protect themselves" ✔️ 

You literally just rendered your entire logic useless. Congratulations!

> But it also applies the same logic - russian had Stalin so the world should bomb russia now?

I'll tell Gitanas to suck his own gentiles now.

**Comment by cpueasy** [comment]
> Taking things personally I see. Now you can go fuck yourself.

![image](https://user-images.githubusercontent.com/88821057/157018147-9057cf21-862c-44b5-b32d-2194d9ff53fe.png)

**Comment by deputinizer** [comment]
I hope @cpueasy goes back here in like 2 years to read what was in his head back then.

<details>
  <summary>[Spoiler] Let me archive all your comments so you can't edit it out</summary>

https://www.google.com/maps/d/u/0/viewer?mid=1DZtmQOsq6UBodj8zgB9WC_9BEaY&ll=47.9415218726191%2C37.54165384070755&z=14
https://www.youtube.com/watch?v=i2ILlui2HmI

![image](https://user-images.githubusercontent.com/100740281/157034990-c6827b93-1003-4d8b-9f96-1968157b02df.png)


man look at these violent hated separatists!
https://en.wikipedia.org/wiki/Casualties_of_the_Russo-Ukrainian_War#:~:text=War%20in%20Donbas,-Main%20article%3A%20War&text=The%20overall%20number%20of%20confirmed,killed%20by%2013%20May%202021
https://www.hrw.org/news/2014/07/24/ukraine-unguided-rockets-killing-civilians
https://ru.wikinews.org/wiki/%D0%92_%D0%93%D0%BE%D1%80%D0%BB%D0%BE%D0%B2%D0%BA%D0%B5_%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D0%BB%D0%B8_%D0%BC%D0%B5%D0%BC%D0%BE%D1%80%D0%B8%D0%B0%D0%BB_%D0%BF%D0%BE%D0%B3%D0%B8%D0%B1%D1%88%D0%B8%D0%BC_%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D1%8F%D0%BC
https://ronin-077.livejournal.com/37466.html
Russia is Defending Ukraine not Invading. Know the truth. STOP SUPPORTING TERRORISM

![image](https://user-images.githubusercontent.com/100740281/157034327-be9347fa-7dd9-466d-863e-101544a14c3c.png)

@baylanger Yeah I'm so PRESSED LOL. It takes 10 seconds for Russia to Press a button and boom no Ukraine. Yet the war has been going on for a a week or so hasn't it? NOW Ask yourself WHY. That's right I can only launch DOS attacks because my skill level is BELOW ZERO and I can't hack anything for crap because I'm a pathetic Lithuanian skid @erkexzcx

Q: Why would Russia care of what is happening in Ukraine in the first place?

A: 15 thousand Russians killed by neo nazi rebels over the past 8 years, nobody give a crap.

Q: Why would only Russia see Ukraine as a problem and not the rest of the world?

A: Search up Ukrainian nationalism and see who you and the rest of the world are supporting. Stephan Bandera is a terrorist btw.

Q: Why Russia reportedly commit war crimes in Ukraine (killing unarmed civilians, shooting into nuclear reactors, shelling cities with civilians)?

A: Where's your proof? I forgot you don't have any. Any Russians Tanks or vehicles have a "Z" for ZAPAD on them to show they are Russian so sending Random Ukrainian tanks running cars over simply won't cut it buddy.

Q: Why Putin continuously threatens non-NATO countries if they join NATO?

A: Did you see what they did to Yugoslavia? Literally worse than Ukraine. Let me Enlighten you.
https://www.youtube.com/watch?v=gelCe981y0I


Putin's 100 billions ruble Palace paid with Russian citizens' money
[Google Satellite View](https://www.google.com/maps/@44.4212736,38.20606,2716m/data=!3m1!1e3)
[Wikipedia](https://en.wikipedia.org/wiki/Putin's_Palace)
You must have a screw loose in your brain because he lives in KREMLIN MOSCOW not in that palace that doesn't belong to him. Monkey brain @baylanger


cpueasy commented 2 hours ago
To everyone reading this - I know this discussion is worthless and @erkexzcx is trying to achieve anything. You can't change brainwashed people by American propaganda just like you can't change

Luckily thanks to me being a lithuanian skid and ddosing russian sites because im harmless and can't hack my way out of a plastic bag they will sort themselves out :)

cpueasy commented 2 hours ago
Video/pictures recordings of actual people who lived those events?
Stories of actual people who lived those events?
Stories of friends/relatives who also lived those events?

I literally sent you everything scroll up lazy clown



cpueasy commented 2 hours ago • 
> Why there are no reports of killed russian's relatives/friends that actually live in Ukraine? Also why there are no neo nazi rebels reports as well? Also Germany said that this is purely bullshit as they are kind of experts in this area. You know there are on nazis in Ukraine.

You're blind and didn't even bother to open my sites I sent you. Stay blind pendoz

> Why should I care about this dude? Zelenski is a president of Ukraine, not some random dude who died more than 50 years ago. According to your logic, Stalin used to be leader of russian territories, so should the rest of the world invade Russia now?

Zelensky is the so called president but one wrong move from him and he's a dead man. He's a puppet to the terrorists that are currently controlling the country. Stalin is completely irrelevant just like your "anti vax" statements I could write you an essay on him but I really got no time for that. In all honesty he's a controversial figure and he even put his own relatives into gulags.

> Let me guess - Stalin did nothing bad? :D even my grandpa would like to disagree with this statement.

Again another Irrelevant statement, Like I could write you a whole essay on how tiny your Lithuania is and how irrelevant it is to the rest of the world. Your grandpa isn't Russian and is also completely irrelevant in this context of conversation.

> Have you been antivaxxer as well? :D Where's your proof? is probably the most childish excuse you can find. Proof:

Hey bro, can you help me find Lithuania on the map? I'm searching for a solid day and I just can't seem to find it anywhere!

> Friends and relatives who live in Ukraine (they have internet and telephones as well).
Friends/relatives of friends/relatives who live in Ukraine (they have internet and telephones as well).
Telegram groups (video recordings, locals feedback, captured russian soldiers and their interrogation).
Actual journalists from non-russian countries reporting the situation from Ukraine.

all your friends see and film are tanks and things getting destroyed. You can't provide me sufficient video evidence to show ANYTHING All those tanks destroying cars don't have the Z symbol, you might as well believe the ghost of Kiev exists you KNOBHEAD . Telegram groups oh yeah more things getting destroyed and random Ukrainians pretending to be Russian? very believable yet you claim that I'm "brainwashed" You're brainwashed you clown for even making this whole repo.

> Yes, tanks with Z are shooting into nuclear reactors and driving over civilian vehicles. On top of that they are shooting into civilians. Everything is shown in video recordings by Ukrainian civilians. But hey, government in Russia knows better, right?

Video proof or it didn't happen. send it to my discord -> cpu_ezy [Zapad Team]#7008. Really everything recorded ayy? Everything everything 100% completely one sided? Well I'm proving your whole point wrong because Russian film too and Russian news exists open_mouth crazy stuff right? Yeah Government in Russia does know better, they got a solid counter terrorism system in place and I completely respect that.

> NATO is defence alliance, not offence. Not sure why do you see a problem with that? From wikipedia After attempts at a diplomatic solution failed, NATO intervened, justifying the campaign as a "humanitarian war". [55] which means don't start a war against NATO and NATO will not bomb you. This includes nuclear reactors, which will definitelly impact NATO countries and NATO must act to protect themselves from nuclear explosions or further aggression against baltic countries.

Oh yeah. Lets bomb Yugoslavia that did nothing wrong with ** NUCLEAR WARHEADS** Because we want to prevent a "humanitarian war" let bomb Heroshima and Nagasaki for the same reason. Just to measure our huge private parts in front of the whole world. "NATO will not bomb you" -- @erkexzcx (Head representative of NATO larping Lithuanian brainwashed skid) says to me. Oh yeah I totally legit 100% believe you speaking from behalf of NATO mhm yes yes clown_face

"NATO must act to protect themselves" -- nah dude it's -> "Russia must act to protect themselves" heavy_check_mark

You literally just rendered your own logic useless. Congratulations!

> But it also applies the same logic - russian had Stalin so the world should bomb russia now?

I'll tell Gitanas to suck his own gentiles now.

</details>

**Comment by erkexzcx** [comment]
Reported to Github for harassment and posting my public info (picture, name, surname) under separate issue. I mean it's easy to find who I am, but this is clearly a harassment.

It also confirms that people who are brainwashed by russian propaganda aren't very smart and tend to take things very personally.

**Comment by erkexzcx** [comment]
> Our review of the account(s) and/or content named in your report has concluded. We have determined that one or more violations of GitHub’s Terms of Service have occurred and have taken appropriate action in response.

**Comment by baylanger** [comment]
@cpueasy - oh I am sad, @cpueasy doesn't work anymore, account suspended 🕺  Maybe we need to @cpu_easy on Twitter.

Q1) @cpueasy Can you name the 5 richest people in Russia and their net worth?

  I'll help you :
    1. Vladimir Potanin , networth 22 billion US$ (that's a lot of ruble)
    2. Vladimir Lisin, 20 billion US$

The palace is worth about 100 billions US$ .

Q2) if Vladimir Potanin is worth 20 billions, who could potentially be the owner [palace](https://en.wikipedia.org/wiki/Putin%27s_Palace) if not the Russian government?  Who has "power" to prevent boats to navigate in the water in front of the palace?


Following the invasion in Ukraine, the following companies and many many more have stepped up against Putin's - some do not deliver products/parts anymore : Apple, Netflix, Nike, Adidas, Walt Disney, BMW, Ford, Volkswagen, all Japanese car companies, Levi Strauss, Nissan, Mastercard, Visa, Microsoft, Samsung, IKEA, Mercedes-Benz, Spotify, SAP, Oracle, H&M, Honda, Dell, Boeing, Bombardier, Exxon, Shell, BP, Paypal, Tiktok and the list goes on.

Around the world, Russian products (vokda, etc) have been removed from store shelf.

Since the invasion, rare the companies interested to buy any Russian product and definitely not bloody oil.

All media/news network in Russia is controlled by the government, right?  Putin is not doing in Ukraine what the medias he controls are telling you.

Q3) If Putin's reasons behind the invasion were so founded, why so many companies & countries are stepping up against Russia?

ps: what Putin tells the world != what the Russian media tells you - it is propaganda.  Hopefully you'll see light at the end of the tunnel before you die - btw the sooner the better.

Q4) Why do you think so many people are fleeing Russia?

Answer : they know what Putin did is really bad.  Instead of blindly trusting the Russian's government owned media, like so many Russians, some are smarter and did their homework.  You know how to use the Internet?  We say you've been brainwashed, take a pause and think twice instead of losing your mind.

McDonald’s and Coca-Cola are still operating in Russia?  Probably not for long due to pressure coming from around the world.

**Comment by baylanger** [comment]
@cpueasy - If you crave for a BigMac , McDonald are closing all restaurants in Russia.  You can again thank Putin for what's happening in your country.

My best advice, please cross check what you get from Sputnik & RT controlled media!

**Comment by baylanger** [comment]
@cpueasy Coca-Cola announced they are out from Russia.

If we can predict the future, perhaps you should listen to us instead of staying brainwashed.

**Comment by baylanger** [comment]
@cpueasy I forgot to share this video with you.

Russian governor [Sergei Tsivilyov](https://m.youtube.com/watch?v=MuXAcsBiEOw)

Putin told Russian soldiers that Ukrainians would welcome them with open arms.  Russia is the one that started this WAR - it is not a special operation.  Turns out that ALL Ukrainians are defending their country against Russia and thousands of Russians including 2 generals have died!  If Ukrainian government was so bad with their citizens, can you explain why they are fighting back Russia?  Are still brainwashed or is your brain starting to wonder if Russia government is so right!

I'm done with you, hope you survive the war.

**Comment by baylanger** [comment]
Updated link.

**Comment by baylanger** [comment]
I was too hard to resist ... I'll probably come back in many years to read this thread!

```
... new documents published by the Kremlin this week suggest that the Russian government is preparing for things to get much worse. The documents reveal that the Kremlin is seeking to eradicate reliance on any Western internet services, potentially isolating itself from the rest of the global internet, a move that would send Russia back to the digital dark ages, further crippling its economy and ending the promise that a free and open internet could act as a check on authoritarian leaders like Vladimir Putin.
On Monday reports circulated on social media that the Kremlin was going to disconnect from the global internet by Friday, March 11, based on two documents published by the Ministry of Digital Development.
```

Russians would be forced to use online services from Russian.  That's a nice way for the government to easily spy on their citizens.  Who'd be surprised, considering all the corruption around Putin and the false narrative on the WAR (not a special operation) - Putin and his regime doesn't want any Russian to know the true about this war.

Russia might need to disconnect their fax machines as well because the West will send you the real news.
