### ISSUE TITLE
додати пріорітети : enhancement

### ISSUE THREAD

**Issue by DjSapsan** [erkexzcx/stoppropaganda#94]
Як корисну фічу можна додати пріорітет на окремі цілі. Там багато сайтів і щоб сили не розбивались на все, можна сфокусувати все на самому головному. По пріорітетам можна робити 100% , або може 50% від усього потенціалу.
Наприклад, https://www.yaplakal.com/ не такий пріорітет, як щось інше. Плюс із-за низького пріорітету, ці сайти так і продовжують працювати, так що немає сенсу без фокусу сил.

**Comment by Toxyl** [comment]
sounds like a good idea, but wouldn't that give those with lower priority more breathing room and thus be detrimental to the general cause?

**Comment by erkexzcx** [comment]
Translation:

> As a useful feature, you can add priority to individual goals. There are many sites and so that the forces are not divided into everything, you can focus on the most important thing. You can do 100% of the priorities, or maybe 50% of the full potential.
For example, https://www.yaplakal.com/ is not as high a priority as anything else. Plus, because of the low priority, these sites continue to operate, so it makes no sense without a focus.

Those websites block IPs that create many connections. This is the reason why traffic is being DROP'ed (resulting in timeout). Unless you are constantly getting HTTP code 2** or 3** - you are right, more priority can be assigned for such sites, but most of them aren't even responding (timing out) and there is no need to prioritize them.

Also let's not forget that the purpose of this application is to make it "easy to use" and not tweaking & configuration nightmare. This is the reason why you don't see configuration files and external lists of websites/DNSes.
